### ISSUE TITLE
Secrets not getting created on new namespaces.

### ISSUE THREAD

**Issue by dsarath2205** [emberstack/kubernetes-reflector#150]
Consider a situation where I have deployed reflector 4 days back and created a namespace after two days. The reflector is only copying secrets to the namespaces that are created 4 days back but it is not performing any action on the namespace which was created two days back. 

Can you please let me how I can configure reflector in a way so that it can copy secrets to the namespaces which are created even after the deployment of reflector.

Config: 
reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ""                                                                                                                            
reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"

**Comment by sdurrheimer** [comment]
Seems a have a similar issue with random new namespaces not getting the reflected secrets. Restarting the reflector solves the issue temporarily.

**Comment by icehaunter** [comment]
I've also encountered the exact same issue unfortunately. At some point Refector just stopped  doing its job for new deployments to new namespaces

**Comment by icehaunter** [comment]
Issue persists, no stale please

**Comment by sdurrheimer** [comment]
bump

**Comment by TaylorChristie** [comment]
I'm still seeing this issue on the latest version (6.1.47). Restarting the pod solves the issue, but I just get the repeated log and no other details
```
2022-05-11 19:00:21.856 +00:00 [INF] (ES.Kubernetes.Reflector.Core.NamespaceWatcher) Canceled using token.
2022-05-11 19:00:21.856 +00:00 [INF] (ES.Kubernetes.Reflector.Core.NamespaceWatcher) Session closed. Duration: 00:01:40.0056000. Faulted: False.
2022-05-11 19:00:21.856 +00:00 [INF] (ES.Kubernetes.Reflector.Core.NamespaceWatcher) Requesting V1Namespace resources
2022-05-11 19:00:53.332 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretWatcher) Canceled using token.
2022-05-11 19:00:53.332 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretWatcher) Session closed. Duration: 00:01:40.0047759. Faulted: False.
2022-05-11 19:00:53.332 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretWatcher) Requesting V1Secret resources
2022-05-11 19:01:24.955 +00:00 [INF] (ES.Kubernetes.Reflector.Core.ConfigMapWatcher) Canceled using token.
2022-05-11 19:01:24.955 +00:00 [INF] (ES.Kubernetes.Reflector.Core.ConfigMapWatcher) Session closed. Duration: 00:01:40.0041689. Faulted: False.
2022-05-11 19:01:24.955 +00:00 [INF] (ES.Kubernetes.Reflector.Core.ConfigMapWatcher) Requesting V1ConfigMap resources
2022-05-11 19:02:01.856 +00:00 [INF] (ES.Kubernetes.Reflector.Core.NamespaceWatcher) Canceled using token.
2022-05-11 19:02:01.857 +00:00 [INF] (ES.Kubernetes.Reflector.Core.NamespaceWatcher) Session closed. Duration: 00:01:40.0001084. Faulted: False.
2022-05-11 19:02:01.857 +00:00 [INF] (ES.Kubernetes.Reflector.Core.NamespaceWatcher) Requesting V1Namespace resources
2022-05-11 19:02:33.330 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretWatcher) Canceled using token.
2022-05-11 19:02:33.330 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretWatcher) Session closed. Duration: 00:01:39.9980486. Faulted: False.
2022-05-11 19:02:33.330 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretWatcher) Requesting V1Secret resources
2022-05-11 19:03:04.958 +00:00 [INF] (ES.Kubernetes.Reflector.Core.ConfigMapWatcher) Canceled using token.
2022-05-11 19:03:04.958 +00:00 [INF] (ES.Kubernetes.Reflector.Core.ConfigMapWatcher) Session closed. Duration: 00:01:40.0032231. Faulted: False.
2022-05-11 19:03:04.958 +00:00 [INF] (ES.Kubernetes.Reflector.Core.ConfigMapWatcher) Requesting V1ConfigMap resources
2022-05-11 19:03:41.860 +00:00 [INF] (ES.Kubernetes.Reflector.Core.NamespaceWatcher) Canceled using token.
2022-05-11 19:03:41.860 +00:00 [INF] (ES.Kubernetes.Reflector.Core.NamespaceWatcher) Session closed. Duration: 00:01:40.0029816. Faulted: False.
2022-05-11 19:03:41.860 +00:00 [INF] (ES.Kubernetes.Reflector.Core.NamespaceWatcher) Requesting V1Namespace resources
2022-05-11 19:04:13.334 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretWatcher) Canceled using token.
2022-05-11 19:04:13.334 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretWatcher) Session closed. Duration: 00:01:40.0033626. Faulted: False.
2022-05-11 19:04:13.334 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretWatcher) Requesting V1Secret resources
2022-05-11 19:04:44.959 +00:00 [INF] (ES.Kubernetes.Reflector.Core.ConfigMapWatcher) Canceled using token.
2022-05-11 19:04:44.960 +00:00 [INF] (ES.Kubernetes.Reflector.Core.ConfigMapWatcher) Session closed. Duration: 00:01:40.0011194. Faulted: False.
2022-05-11 19:04:44.960 +00:00 [INF] (ES.Kubernetes.Reflector.Core.ConfigMapWatcher) Requesting V1ConfigMap resources
2022-05-11 19:05:21.859 +00:00 [INF] (ES.Kubernetes.Reflector.Core.NamespaceWatcher) Canceled using token.
2022-05-11 19:05:21.859 +00:00 [INF] (ES.Kubernetes.Reflector.Core.NamespaceWatcher) Session closed. Duration: 00:01:39.9991666. Faulted: False.
2022-05-11 19:05:21.860 +00:00 [INF] (ES.Kubernetes.Reflector.Core.NamespaceWatcher) Requesting V1Namespace resources
2022-05-11 19:05:53.339 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretWatcher) Canceled using token.
2022-05-11 19:05:53.339 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretWatcher) Session closed. Duration: 00:01:40.0054144. Faulted: False.
2022-05-11 19:05:53.339 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretWatcher) Requesting V1Secret resources
2022-05-11 19:06:24.963 +00:00 [INF] (ES.Kubernetes.Reflector.Core.ConfigMapWatcher) Canceled using token.
2022-05-11 19:06:24.963 +00:00 [INF] (ES.Kubernetes.Reflector.Core.ConfigMapWatcher) Session closed. Duration: 00:01:40.0035626. Faulted: False.
2022-05-11 19:06:24.963 +00:00 [INF] (ES.Kubernetes.Reflector.Core.ConfigMapWatcher) Requesting V1ConfigMap resources
2022-05-11 19:07:01.860 +00:00 [INF] (ES.Kubernetes.Reflector.Core.NamespaceWatcher) Canceled using token.
2022-05-11 19:07:01.860 +00:00 [INF] (ES.Kubernetes.Reflector.Core.NamespaceWatcher) Session closed. Duration: 00:01:40.0002169. Faulted: False.
2022-05-11 19:07:01.861 +00:00 [INF] (ES.Kubernetes.Reflector.Core.NamespaceWatcher) Requesting V1Namespace resources
2022-05-11 19:07:33.340 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretWatcher) Canceled using token.
2022-05-11 19:07:33.340 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretWatcher) Session closed. Duration: 00:01:40.0007353. Faulted: False.
2022-05-11 19:07:33.340 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretWatcher) Requesting V1Secret resources
2022-05-11 19:08:04.961 +00:00 [INF] (ES.Kubernetes.Reflector.Core.ConfigMapWatcher) Canceled using token.
2022-05-11 19:08:04.961 +00:00 [INF] (ES.Kubernetes.Reflector.Core.ConfigMapWatcher) Session closed. Duration: 00:01:39.9981792. Faulted: False.
2022-05-11 19:08:04.962 +00:00 [INF] (ES.Kubernetes.Reflector.Core.ConfigMapWatcher) Requesting V1ConfigMap resources
2022-05-11 19:08:41.867 +00:00 [INF] (ES.Kubernetes.Reflector.Core.NamespaceWatcher) Canceled using token.
2022-05-11 19:08:41.867 +00:00 [INF] (ES.Kubernetes.Reflector.Core.NamespaceWatcher) Session closed. Duration: 00:01:40.0061617. Faulted: False.
2022-05-11 19:08:41.867 +00:00 [INF] (ES.Kubernetes.Reflector.Core.NamespaceWatcher) Requesting V1Namespace resources
```

**Comment by mr-davidc** [comment]
I'm in a similar boat as @TaylorChristie.

Reflector is running but when cert-manager eventually creates the TLS secret (there is a significant delay since cert-manager takes time to verify the CertificateRequest), Reflector doesn't seem to realise that this new TLS secret has been created and fails to replicate it to a newly created namespace when a deployment occurs.

Restarting the pod does make the secret sync across but this shouldnt be required?

**Comment by michalgoldys** [comment]
Up - we got the same situation.

**Comment by liewwy19** [comment]
we had the same situation today on one of our cluster ...

**Comment by blackliner** [comment]
same here 😞

**Comment by winromulus** [comment]
@blackliner are you running the latest version?

**Comment by blackliner** [comment]
Helm chart version v7.0.151

**Comment by winromulus** [comment]
Try the latest please and let me know if the issue with the secrets watcher is fixed.

**Comment by UntouchedWagons** [comment]
I'm using v7.1.216 and nothing's happening. The Secret that Cert-Manager makes has the correct annotations.

**Comment by alteredtech** [comment]
Not having secrets populate to other namespaces either.
Running reflector 7.1.262
k3s v1.29.2+k3s1

Installed on default namespace
```
> kubectl describe deployment reflector
Name:                   reflector
Namespace:              default
CreationTimestamp:      Thu, 04 Jul 2024 16:27:36 -0600
Labels:                 app.kubernetes.io/instance=reflector
                        app.kubernetes.io/managed-by=Helm
                        app.kubernetes.io/name=reflector
                        app.kubernetes.io/version=7.1.262
                        helm.sh/chart=reflector-7.1.262
Annotations:            deployment.kubernetes.io/revision: 2
                        meta.helm.sh/release-name: reflector
                        meta.helm.sh/release-namespace: default
Selector:               app.kubernetes.io/instance=reflector,app.kubernetes.io/name=reflector
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           app.kubernetes.io/instance=reflector
                    app.kubernetes.io/name=reflector
  Annotations:      kubectl.kubernetes.io/restartedAt: 2024-07-04T17:26:34-06:00
  Service Account:  reflector
  Containers:
   reflector:
    Image:      emberstack/kubernetes-reflector:7.1.262
    Port:       25080/TCP
    Host Port:  0/TCP
    Liveness:   http-get http://:http/healthz delay=5s timeout=1s period=10s #success=1 #failure=3
    Readiness:  http-get http://:http/healthz delay=5s timeout=1s period=10s #success=1 #failure=3
    Startup:    http-get http://:http/healthz delay=0s timeout=1s period=5s #success=1 #failure=10
    Environment:
      ES_Serilog__MinimumLevel__Default:        Information
      ES_Reflector__Watcher__Timeout:           
      ES_Reflector__Kubernetes__SkipTlsVerify:  false
    Mounts:                                     <none>
  Volumes:                                      <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  reflector-9d6b579bf (0/0 replicas created)
NewReplicaSet:   reflector-756b9c7795 (1/1 replicas created)
Events:
  Type    Reason             Age    From                   Message
  ----    ------             ----   ----                   -------
  Normal  ScalingReplicaSet  63m    deployment-controller  Scaled up replica set reflector-9d6b579bf to 1
  Normal  ScalingReplicaSet  5m1s   deployment-controller  Scaled up replica set reflector-756b9c7795 to 1
  Normal  ScalingReplicaSet  4m50s  deployment-controller  Scaled down replica set reflector-9d6b579bf to 0 from 1
```

One of my cert yaml files
```
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: stage-demo-example-io
  namespace: default
spec:
  secretTemplate:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "external-hosts, traefik, default"
  secretName: stage-demo-example-io-tls
  issuerRef:
    name: letsencrypt-stage
    kind: ClusterIssuer
  commonName: "*.demo.example.io"
  dnsNames:
  - "demo.example.io"
  - "*.demo.example.io"
```

Secrets in default
```
> kubectl get secret
NAME                              TYPE                 DATA   AGE
digitalocean-dns                  Opaque               1      18h
prod-demo-example-io-tls          kubernetes.io/tls    2      17h
sh.helm.release.v1.reflector.v1   helm.sh/release.v1   1      66m
stage-demo-example-io-tls         kubernetes.io/tls    2      18h
stage-home-example-io-tls         kubernetes.io/tls    2      9h
```

Then empty secrets in external-hosts
```
> kubectl get secret -n external-hosts
No resources found in external-hosts namespace.
```

Logs from the reflector pod
```
> kubectl logs reflector-756b9c7795-btzcr
2024-07-04 23:26:39.223 +00:00 [INF] () Starting host
2024-07-04 23:26:39.533 +00:00 [INF] (ES.Kubernetes.Reflector.Core.NamespaceWatcher) Requesting V1Namespace resources
2024-07-04 23:26:39.552 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretWatcher) Requesting V1Secret resources
2024-07-04 23:26:39.562 +00:00 [INF] (ES.Kubernetes.Reflector.Core.ConfigMapWatcher) Requesting V1ConfigMap resources
```

**Comment by alteredtech** [comment]
AHHH I figured out my issue. I over read the 'auto' part in the annotations. 
I needed to have this
```
  secretTemplate:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "external-hosts, traefik, default"
```

**Comment by cooervo** [comment]
this is still happening in v7.1.288

**Comment by winromulus** [comment]
@cooervo  please upgrade to 9.x (latest) please

**Comment by cooervo** [comment]
I updated to  yesterday`9.0.313` and it stopped updating secrets today am getting this error in the `reflector` pod

```
2025-02-26 20:55:59.490 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretWatcher) Session closed. Duration: 00:00:00.6541375. Faulted: True.
2025-02-26 20:56:04.491 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretWatcher) Requesting V1Secret resources
2025-02-26 20:56:05.259 +00:00 [ERR] (ES.Kubernetes.Reflector.Core.SecretWatcher) Faulted due to exception.
System.Text.RegularExpressions.RegexParseException: Invalid pattern '*-db' at offset 1. Quantifier '*' following nothing.
at System.Text.RegularExpressions.RegexParser.ScanRegex()
at System.Text.RegularExpressions.RegexParser.Parse(String pattern, RegexOptions options, CultureInfo culture)
at System.Text.RegularExpressions.Regex..ctor(String pattern, CultureInfo culture)
at System.Text.RegularExpressions.RegexCache.GetOrAdd(String pattern)
at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
at System.Linq.Enumerable.ArrayWhereSelectIterator`2.ToList(ReadOnlySpan`1 source, Func`2 predicate, Func`2 selector)
at System.Linq.Enumerable.ListWhereSelectIterator`2.ToList()
at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
at ES.Kubernetes.Reflector.Core.Mirroring.ResourceMirror`1.AutoReflectionForSource(KubeRef resourceRef, TResource resourceInstance, CancellationToken cancellationToken) in /src/ES.Kubernetes.Reflector/Core/Mirroring/ResourceMirror.cs:line 348
at ES.Kubernetes.Reflector.Core.Mirroring.ResourceMirror`1.HandleUpsert(TResource resource, CancellationToken cancellationToken) in /src/ES.Kubernetes.Reflector/Core/Mirroring/ResourceMirror.cs:line 219
at ES.Kubernetes.Reflector.Core.Mirroring.ResourceMirror`1.Handle(WatcherEvent notification, CancellationToken cancellationToken) in /src/ES.Kubernetes.Reflector/Core/Mirroring/ResourceMirror.cs:line 76
at MediatR.NotificationPublishers.ForeachAwaitPublisher.Publish(IEnumerable`1 handlerExecutors, INotification notification, CancellationToken cancellationToken)
at ES.Kubernetes.Reflector.Core.Watchers.WatcherBackgroundService`2.ExecuteAsync(CancellationToken stoppingToken) in /src/ES.Kubernetes.Reflector/Core/Watchers/WatcherBackgroundService.cs:line 49
at ES.Kubernetes.Reflector.Core.Watchers.WatcherBackgroundService`2.ExecuteAsync(CancellationToken stoppingToken) in /src/ES.Kubernetes.Reflector/Core/Watchers/WatcherBackgroundService.cs:line 48
2025-02-26 20:56:05.260 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretWatcher) Session closed. Duration: 00:00:00.7694113. Faulted: True.
2025-02-26 20:56:10.260 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretWatcher) Requesting V1Secret resources
2025-02-26 20:56:11.197 +00:00 [ERR] (ES.Kubernetes.Reflector.Core.SecretWatcher) Faulted due to exception.
System.Text.RegularExpressions.RegexParseException: Invalid pattern '*-db' at offset 1. Quantifier '*' following nothing.
at System.Text.RegularExpressions.RegexParser.ScanRegex()
at System.Text.RegularExpressions.RegexParser.Parse(String pattern, RegexOptions options, CultureInfo culture)
at System.Text.RegularExpressions.Regex..ctor(String pattern, CultureInfo culture)
at System.Text.RegularExpressions.RegexCache.GetOrAdd(String pattern)
at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
at System.Linq.Enumerable.ArrayWhereSelectIterator`2.ToList(ReadOnlySpan`1 source, Func`2 predicate, Func`2 selector)
at System.Linq.Enumerable.ListWhereSelectIterator`2.ToList()
at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
at ES.Kubernetes.Reflector.Core.Mirroring.ResourceMirror`1.AutoReflectionForSource(KubeRef resourceRef, TResource resourceInstance, CancellationToken cancellationToken) in /src/ES.Kubernetes.Reflector/Core/Mirroring/ResourceMirror.cs:line 348
at ES.Kubernetes.Reflector.Core.Mirroring.ResourceMirror`1.HandleUpsert(TResource resource, CancellationToken cancellationToken) in /src/ES.Kubernetes.Reflector/Core/Mirroring/ResourceMirror.cs:line 219
at ES.Kubernetes.Reflector.Core.Mirroring.ResourceMirror`1.Handle(WatcherEvent notification, CancellationToken cancellationToken) in /src/ES.Kubernetes.Reflector/Core/Mirroring/ResourceMirror.cs:line 76
at MediatR.NotificationPublishers.ForeachAwaitPublisher.Publish(IEnumerable`1 handlerExecutors, INotification notification, CancellationToken cancellationToken)
at ES.Kubernetes.Reflector.Core.Watchers.WatcherBackgroundService`2.ExecuteAsync(CancellationToken stoppingToken) in /src/ES.Kubernetes.Reflector/Core/Watchers/WatcherBackgroundService.cs:line 49
at ES.Kubernetes.Reflector.Core.Watchers.WatcherBackgroundService`2.ExecuteAsync(CancellationToken stoppingToken) in /src/ES.Kubernetes.Reflector/Core/Watchers/WatcherBackgroundService.cs:line 48
2025-02-26 20:56:11.198 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretWatcher) Session closed. Duration: 00:00:00.9378838. Faulted: True.
```

**Comment by vandervieira** [comment]
this is still happening in v9.0.322

**Comment by winromulus** [comment]
@vandervieira  can you set the log level to Debug please and post the logs please?

**Comment by vandervieira** [comment]
@winromulus Kubernetes Version: v1.28.15+rke2r1
I adjusted for debug, but the pod does not display logs. I tested on version v7.1.288 with debug, and the secrets work, and it displays logs (the secrets have not changed). Therefore, I am currently using reflector version v7.1.288, which works in my environment.

**Comment by abhinav1107** [comment]
Faced the same issue of not syncing secrets in newly created namespaces. I can confirm that downgrading to `v7.1.288` works.

**Comment by aldag75** [comment]
I have the same problem.   With version 9.x  the reflection is done once per hour..  doesn't matter if I create new namespace 
```
2025-04-01 10:40:31.874 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretWatcher) Session closed. Duration: 01:00:00.1124897. Faulted: False.
2025-04-01 10:40:31.874 +00:00 [INF] (ES.Kubernetes.Reflector.Core.ConfigMapWatcher) Session closed. Duration: 01:00:00.1119208. Faulted: False.
2025-04-01 10:40:31.874 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretWatcher) Requesting V1Secret resources
2025-04-01 10:40:31.874 +00:00 [INF] (ES.Kubernetes.Reflector.Core.ConfigMapWatcher) Requesting V1ConfigMap resources
2025-04-01 10:40:31.880 +00:00 [INF] (ES.Kubernetes.Reflector.Core.NamespaceWatcher) Session closed. Duration: 01:00:00.1204900. Faulted: False.
2025-04-01 10:40:31.881 +00:00 [INF] (ES.Kubernetes.Reflector.Core.NamespaceWatcher) Requesting V1Namespace resources
2025-04-01 10:40:32.204 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretMirror) Auto-reflected cert-manager/ingress-domain-cert where permitted. Created 0 - Updated 0 - Deleted 0 - Validated 57.
2025-04-01 11:40:31.990 +00:00 [INF] (ES.Kubernetes.Reflector.Core.ConfigMapWatcher) Session closed. Duration: 01:00:00.1158737. Faulted: False.
2025-04-01 11:40:31.990 +00:00 [INF] (ES.Kubernetes.Reflector.Core.NamespaceWatcher) Session closed. Duration: 01:00:00.1093820. Faulted: False.
2025-04-01 11:40:31.990 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretWatcher) Session closed. Duration: 01:00:00.1159695. Faulted: False.
2025-04-01 11:40:31.991 +00:00 [INF] (ES.Kubernetes.Reflector.Core.ConfigMapWatcher) Requesting V1ConfigMap resources
2025-04-01 11:40:31.991 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretWatcher) Requesting V1Secret resources
2025-04-01 11:40:31.991 +00:00 [INF] (ES.Kubernetes.Reflector.Core.NamespaceWatcher) Requesting V1Namespace resources
2025-04-01 11:40:32.415 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretMirror) Created xagr-test/ingress-domain-cert as a reflection of cert-manager/ingress-domain-cert
2025-04-01 11:40:32.415 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretMirror) Auto-reflected cert-manager/ingress-domain-cert where permitted. Created 1 - Updated 0 - Deleted 0 - Validated 57.
```
It works OK with version 7.1.288.  When new namespace is created the secrets are reflected immediately.

**Comment by aldag75** [comment]
The 1 hour delay is related to params `configuration.watcher.timeout` , which default is 3600... if I set it to 60  it restarts the watchers sessions every 1 minute  and the reflections are performed. But this is not the expected behaviour.

**Comment by stucki-stuck** [comment]
Hello folks, 
looks fixed in the latest version !
