### ISSUE TITLE
Expanded Letsencrypt certificate chain breaks kubernetes-reflector

### ISSUE THREAD

**Issue by scarby** [emberstack/kubernetes-reflector#191]
As mentioned [here](https://community.letsencrypt.org/t/providing-a-longer-certificate-chain-by-default/148738) of may 4th letsencrypt increased the size of their certificate chain and are now including 3 certificates rather than 2.

This causes the reflector to fail when watching the secret and never update secrets in other namespaces.

In this case this is evidenced by the following error message:
```
2021-06-21 19:05:33.626 +00:00 [ERR] (ES.Kubernetes.Reflector.Secrets.VMwareMirror) V1Secret watcher  Faulted
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.String.Ctor(Char[] value, Int32 startIndex, Int32 length)
   at Newtonsoft.Json.JsonTextReader.ParseReadString(Char quote, ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.Skip()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetExtensionData(JsonObjectContract contract, JsonProperty member, JsonReader reader, String memberName, Object o)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Microsoft.Rest.Serialization.SafeJsonConvert.DeserializeObject[T](String json, JsonSerializerSettings settings)
   at k8s.Watcher`1.WatcherLoop(CancellationToken cancellationToken)
```

as cert manager now provides these by default this breaks any cert-manager integration. Also should we only reflect a 2 certificate chain we will lose compatibility with older android operating systems

This may be the cause of #187 

@winromulus are you able to help here?

**Comment by brokenjacobs** [comment]
I'm also interested in a fix here.
