### ISSUE TITLE
Error at Startup

### ISSUE THREAD

**Issue by texasbobs** [emberstack/kubernetes-reflector#208]
We just redeployed version 5.4.17 and randomly seem to be getting this error that prevents the pod from starting.  Any ideas on what to look for or what causes this would be appreciated.

```
2021-09-14 14:08:27.708 +00:00 [ERR] (Microsoft.AspNetCore.Server.Kestrel) Connection id “0HMBNH40FEP2D”, Request id “0HMBNH40FEP2D:00000001": An unhandled exception was thrown by the application.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService.CheckHealthAsync(Func`2 predicate, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Diagnostics.HealthChecks.HealthCheckMiddleware.InvokeAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by texasbobs** [comment]
Looking like this is a dead repo at this point.  Anyone still maintaining this?
