### ISSUE TITLE
OperationCanceledException after long running

### ISSUE THREAD

**Issue by sc250024** [emberstack/kubernetes-reflector#21]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**

I've found that the reflector works great for around 99% of the time. However, I have noticed that after running for a while, I run into the following exception in the pod logs:

```
2020-03-05 14:44:43.396 +00:00 [INF] () Host starting
2020-03-05 14:44:43.695 +00:00 [INF] (ES.Kubernetes.Reflector.Startup) CertManager extension enabled: True
2020-03-05 14:44:49.814 +00:00 [INF] (ES.Kubernetes.Reflector.CertManager.Monitor) V1beta1CustomResourceDefinition Certificate in group cert-manager.io versions updated to ["v1alpha2"]
2020-03-09 12:55:50.609 +00:00 [ERR] (Microsoft.AspNetCore.Server.Kestrel) Connection id "0HLU12F0TC7N8", Request id "0HLU12F0TC7N8:00000001": An unhandled exception was thrown by the application.
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService.CheckHealthAsync(Func`2 predicate, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Diagnostics.HealthChecks.HealthCheckMiddleware.InvokeAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

In this case, this happened on March 9th, but I'm just noticing it now because I created a new namespace, and certain secrets weren't reflected there.

The "fix" is to simply kill the pod. Afterwards the application picks up where it left off:

```
2020-03-10 09:10:42.011 +00:00 [INF] () Host starting
2020-03-10 09:10:42.341 +00:00 [INF] (ES.Kubernetes.Reflector.Startup) CertManager extension enabled: True
2020-03-10 09:10:47.827 +00:00 [INF] (ES.Kubernetes.Reflector.CertManager.Monitor) V1beta1CustomResourceDefinition Certificate in group cert-manager.io versions updated to ["v1alpha2"]
2020-03-10 09:10:56.999 +00:00 [INF] (ES.Kubernetes.Reflector.Secrets.Mirror) Created reflection Secret for cert-manager/star-mycompany-io-ecc-tls in namespace my-new-namespace.
2020-03-10 09:11:05.280 +00:00 [INF] (ES.Kubernetes.Reflector.Secrets.Mirror) Created reflection Secret for cert-manager/star-infra-mycompany-io-ecc-tls in namespace my-new-namespace.
2020-03-10 09:11:23.202 +00:00 [INF] (ES.Kubernetes.Reflector.Secrets.Mirror) Created reflection Secret for cert-manager/star-mycompany-com-ecc-tls in namespace my-new-namespace.
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

To be honest, I'm not sure how to reproduce this, other than running the Reflector for a while, and let the error crop up.

* **What is the expected behavior?**

The reflector should run as normal, and if it encounters errors like this, handle that exception. I'm sure it already does this (I don't want to be ungrateful 😊) but this exception seems to cause an issue because the entire application stops working.

* **Please tell us about your environment:**
  
  - **Version:** `emberstack/es.kubernetes.reflector:release-3.19304.10`
  - **Kubernetes version:** AWS EKS 1.14.9
  - **Helm chart version:** `helm.sh/chart: reflector-3.19315.2`

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Thank you for this great app!

**Comment by winromulus** [comment]
@sc250024 I'll investigate this, just need a way to try to reproduce it (quickly).
I think it's due to the health checks that run periodically being cancelled.

**Comment by sc250024** [comment]
@winromulus Thank you! Let me know how I can help.

**Comment by winromulus** [comment]
Hi @sc250024 
Please test v4.1.9. I think the health probes were fixed but I cannot reproduce the original issue either way.
If this continues to be a problem, please reopen this issue and I'll send you a Slack invite so we can debug together (and maybe share more logs privately).
I would love to say that this was definitely fixed, but I can only wait to see if this is still an issue.

**Comment by sc250024** [comment]
@winromulus Deployed v4.1.9, and turned on debug logging. In case this occurs again, I'll hopefully have more information. Thank you very much!
