### ISSUE TITLE
System.InvalidOperationException: A task may only be disposed if it is in a completion state (RanToCompletion, Faulted or Canceled).

### ISSUE THREAD

**Issue by jlsalvador** [emberstack/kubernetes-reflector#251]
|          |                                        |
| -------- | -------------------------------------- |
| K8s      | v1.23.1                                |
| Arch     | x86_64 & aarch64                       |
| Platform | Linux                                  |
| Image    | emberstack/kubernetes-reflector:6.1.16 |

```
2022-01-09 01:22:40.498 +00:00 [INF] () Starting host
2022-01-09 01:23:00.503 +00:00 [INF] (ES.Kubernetes.Reflector.Core.NamespaceWatcher) Requesting V1Namespace resources
2022-01-09 01:23:04.997 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretWatcher) Requesting V1Secret resources
2022-01-09 01:23:05.200 +00:00 [INF] (ES.Kubernetes.Reflector.Core.ConfigMapWatcher) Requesting V1ConfigMap resources
2022-01-09 01:23:08.395 +00:00 [ERR] (ES.Kubernetes.Reflector.Core.ConfigMapWatcher) Faulted due to exception.
System.InvalidOperationException: A task may only be disposed if it is in a completion state (RanToCompletion, Faulted or Canceled).
   at System.Threading.Tasks.Task.Dispose(Boolean disposing)
   at System.Threading.Tasks.Task.Dispose()
   at ES.Kubernetes.Reflector.Core.Watchers.WatcherBackgroundService`2.ExecuteAsync(CancellationToken stoppingToken) in /src/ES.Kubernetes.Reflector/Core/Watchers/WatcherBackgroundService.cs:line 45
2022-01-09 01:23:12.195 +00:00 [INF] (ES.Kubernetes.Reflector.Core.ConfigMapWatcher) Session closed. Duration: 00:00:06.7995435. Faulted: True.
2022-01-09 01:23:14.103 +00:00 [ERR] (ES.Kubernetes.Reflector.Core.SecretWatcher) Faulted due to exception.
System.InvalidOperationException: A task may only be disposed if it is in a completion state (RanToCompletion, Faulted or Canceled).
   at System.Threading.Tasks.Task.Dispose(Boolean disposing)
   at System.Threading.Tasks.Task.Dispose()
   at ES.Kubernetes.Reflector.Core.Watchers.WatcherBackgroundService`2.ExecuteAsync(CancellationToken stoppingToken) in /src/ES.Kubernetes.Reflector/Core/Watchers/WatcherBackgroundService.cs:line 45
2022-01-09 01:23:14.301 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretWatcher) Session closed. Duration: 00:00:09.2987843. Faulted: True.
2022-01-09 01:23:14.304 +00:00 [ERR] (ES.Kubernetes.Reflector.Core.NamespaceWatcher) Faulted due to exception.
System.InvalidOperationException: A task may only be disposed if it is in a completion state (RanToCompletion, Faulted or Canceled).
   at System.Threading.Tasks.Task.Dispose(Boolean disposing)
   at System.Threading.Tasks.Task.Dispose()
   at ES.Kubernetes.Reflector.Core.Watchers.WatcherBackgroundService`2.ExecuteAsync(CancellationToken stoppingToken) in /src/ES.Kubernetes.Reflector/Core/Watchers/WatcherBackgroundService.cs:line 45
2022-01-09 01:23:14.401 +00:00 [INF] (ES.Kubernetes.Reflector.Core.NamespaceWatcher) Session closed. Duration: 00:00:14.0042837. Faulted: True.
```

**Comment by winromulus** [comment]
Hi @jlsalvador 
I think there's something wrong/differently configured with your k8s setup.
From the longs I'm getting that subscriber channels are being closed off after less than 10 seconds by the API server OR you have an unstable network between the node hosting reflector and the control-plane nodes.
Can you provide more details into your setup? Is this on-prem/cloud hosted etc?

I upgraded my clusters to 1.23.1 to make sure this was not a k8s version and it works properly on all clusters (been monitoring them for ~6 hours and all channels close properly after ~40 minutes).

**Comment by winromulus** [comment]
Also can you provide the kubectl describe logs for the pod (specifically the bottom part for events). It might be that the pod gets killed for some reason (resources available or health/readiness checks).

**Comment by jlsalvador** [comment]
> Also can you provide the kubectl describe logs for the pod (specifically the bottom part for events). It might be that the pod gets killed for some reason (resources available or health/readiness checks).

Of course!

```shell
$ kubectl logs -n kube-reflector reflector-54c44f886f-rz24s -f
2022-01-09 13:24:27.305 +00:00 [INF] () Starting host
2022-01-09 13:24:45.897 +00:00 [INF] (ES.Kubernetes.Reflector.Core.NamespaceWatcher) Requesting V1Namespace resources
2022-01-09 13:24:48.698 +00:00 [ERR] (ES.Kubernetes.Reflector.Core.NamespaceWatcher) Faulted due to exception.
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Threading.CancellationToken.ThrowIfCancellationRequested()
   at k8s.Kubernetes.SendRequestRaw(String requestContent, HttpRequestMessage httpRequest, CancellationToken cancellationToken)
   at k8s.Kubernetes.ListNamespaceWithHttpMessagesAsync(Nullable`1 allowWatchBookmarks, String continueParameter, String fieldSelector, String labelSelector, Nullable`1 limit, String resourceVersion, String resourceVersionMatch, Nullable`1 timeoutSeconds, Nullable`1 watch, Nullable`1 pretty, IDictionary`2 customHeaders, CancellationToken cancellationToken)
   at k8s.WatcherExt.<>c__DisplayClass1_0`2.<<MakeStreamReaderCreator>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at k8s.Watcher`1.CreateWatchEventEnumerator(Func`1 streamReaderCreator, Action`1 onError, CancellationToken cancellationToken)+MoveNext()
   at k8s.Watcher`1.CreateWatchEventEnumerator(Func`1 streamReaderCreator, Action`1 onError, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at ES.Kubernetes.Reflector.Core.Watchers.WatcherBackgroundService`2.ExecuteAsync(CancellationToken stoppingToken) in /src/ES.Kubernetes.Reflector/Core/Watchers/WatcherBackgroundService.cs:line 45
   at ES.Kubernetes.Reflector.Core.Watchers.WatcherBackgroundService`2.ExecuteAsync(CancellationToken stoppingToken) in /src/ES.Kubernetes.Reflector/Core/Watchers/WatcherBackgroundService.cs:line 45
2022-01-09 13:24:57.199 +00:00 [INF] (ES.Kubernetes.Reflector.Core.NamespaceWatcher) Session closed. Duration: 00:00:11.7015641. Faulted: True.
2022-01-09 13:24:58.097 +00:00 [FTL] () Host terminated unexpectedly
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at ES.Kubernetes.Reflector.Core.Watchers.WatcherBackgroundService`2.ExecuteAsync(CancellationToken stoppingToken) in /src/ES.Kubernetes.Reflector/Core/Watchers/WatcherBackgroundService.cs:line 75
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Program.<Main>$(String[] args) in /src/ES.Kubernetes.Reflector/Program.cs:line 83

$ kubectl describe pod -n kube-reflector reflector-54c44f886f-rz24s                                                                                              
Name:         reflector-54c44f886f-rz24s
Namespace:    kube-reflector
Priority:     0
Node:         macmini/192.168.2.190
Start Time:   Sun, 09 Jan 2022 14:24:15 +0100
Labels:       app.kubernetes.io/instance=reflector
              app.kubernetes.io/name=reflector
              pod-template-hash=54c44f886f
Annotations:  cni.projectcalico.org/containerID: 5482290ab288e1f4da08c1a18b70014f22983287073fe17bda1202d012f063d3
              cni.projectcalico.org/podIP: 10.244.96.58/32
              cni.projectcalico.org/podIPs: 10.244.96.58/32
              kubectl.kubernetes.io/restartedAt: 2021-06-03T01:16:32+02:00
Status:       Running
IP:           10.244.96.58
IPs:
  IP:           10.244.96.58
Controlled By:  ReplicaSet/reflector-54c44f886f
Containers:
  reflector:
    Container ID:   containerd://822153685cad9f4be7d1a817275702a80af59e7892b82ec9bdb11f7cb68387b2
    Image:          emberstack/kubernetes-reflector:latest
    Image ID:       docker.io/emberstack/kubernetes-reflector@sha256:b44d467de66567636c56ae73df88d6e67b16db19987fa3390b47168b3129736a
    Port:           25080/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Sun, 09 Jan 2022 14:26:30 +0100
    Last State:     Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Sun, 09 Jan 2022 14:25:41 +0100
      Finished:     Sun, 09 Jan 2022 14:26:27 +0100
    Ready:          False
    Restart Count:  3
    Limits:
      cpu:     100m
      memory:  128Mi
    Requests:
      cpu:      100m
      memory:   128Mi
    Liveness:   http-get http://:http/healthz delay=5s timeout=1s period=10s #success=1 #failure=3
    Readiness:  http-get http://:http/healthz delay=5s timeout=1s period=10s #success=1 #failure=3
    Environment:
      ES_Serilog__MinimumLevel__Default:  Information
      ES_Reflector__Watcher__Timeout:     
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-nr2kx (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  kube-api-access-nr2kx:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Guaranteed
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  2m36s                default-scheduler  Successfully assigned kube-reflector/reflector-54c44f886f-rz24s to macmini
  Warning  Unhealthy  95s (x4 over 2m25s)  kubelet            Readiness probe failed: Get "http://10.244.96.58:25080/healthz": dial tcp 10.244.96.58:25080: connect: connection refused
  Warning  Unhealthy  95s (x4 over 2m25s)  kubelet            Liveness probe failed: Get "http://10.244.96.58:25080/healthz": dial tcp 10.244.96.58:25080: connect: connection refused
  Warning  Unhealthy  84s (x2 over 2m4s)   kubelet            Liveness probe failed: Get "http://10.244.96.58:25080/healthz": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  Normal   Killing    84s (x2 over 2m4s)   kubelet            Container reflector failed liveness probe, will be restarted
  Warning  Unhealthy  83s (x4 over 2m4s)   kubelet            Readiness probe failed: Get "http://10.244.96.58:25080/healthz": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  Normal   Pulled     71s (x3 over 2m33s)  kubelet            Container image "emberstack/kubernetes-reflector:latest" already present on machine
  Normal   Created    70s (x3 over 2m32s)  kubelet            Created container reflector
  Normal   Started    69s (x3 over 2m31s)  kubelet            Started container reflector
```

**Comment by winromulus** [comment]
Okay so the problem is clearly from the health probes (see Events). Basically k8s sends a kill signal to the pod.
Are you installing reflector with helm or manifests?

**Comment by jlsalvador** [comment]
> Okay so the problem is clearly from the health probes (see Events). Basically k8s sends a kill signal to the pod. Are you installing reflector with helm or manifests?

Helm.

**Comment by jlsalvador** [comment]
> Okay so the problem is clearly from the health probes (see Events). Basically k8s sends a kill signal to the pod. Are you installing reflector with helm or manifests?

Yes!
You're right. After remove the probes, everything works correctly.
I'm going to set the Values.yaml livenessProbe.initialDelaySeconds. Thanks again @winromulus !

**Comment by jlsalvador** [comment]
@winromulus What do you think about include a `startupProbe` to the https://github.com/emberstack/kubernetes-reflector/blob/main/src/helm/reflector/templates/deployment.yaml ?

**Comment by winromulus** [comment]
@jlsalvador if you don't mind adding it, I'd be more than happy to review.
It will need helm checks to support k8s api version
I'm curious though why there's such a startup delay on your config (is this a low-end machine like a raspberry PI or something?)

**Comment by jlsalvador** [comment]
> @jlsalvador if you don't mind adding it, I'd be more than happy to review. It will need helm checks to support k8s api version I'm curious though why there's such a startup delay on your config (is this a low-end machine like a raspberry PI or something?)

I take your word! (expect from me a PR ASAP).
Yes, I'm currently testing extreme conditions (network, storage, etc) for different apps. This instance has a deliberately extreme slow storage (4Mb/s RW).

**Comment by winromulus** [comment]
Hmm, weird that it affected probes (maybe kubelet had delays in writing logs or something).
