### ISSUE TITLE
Container start fails in k3d on Apple MacBook

### ISSUE THREAD

**Issue by conradreisch** [emberstack/kubernetes-reflector#273]
I'm trying to use relector on a Apple MacBook with M1Pro chip in a K3d cluster with Colima.
Does anyone know a reason for this? Since, the image is ARM64 ready, it should be unrelated to the architecture, right?

```
2022-03-28 11:58:15.483 +00:00 [INF] () Starting host
2022-03-28 11:58:15.887 +00:00 [FTL] () Host terminated unexpectedly
System.IO.IOException: Function not implemented
   at System.IO.FileSystemWatcher.StartRaisingEvents()
   at System.IO.FileSystemWatcher.StartRaisingEventsIfNotDisposed()
   at System.IO.FileSystemWatcher.set_EnableRaisingEvents(Boolean value)
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.TryEnableFileSystemWatcher()
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.CreateFileChangeToken(String filter)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider.Watch(String filter)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.<.ctor>b__1_0()
   at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider..ctor(FileConfigurationSource source)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.Build(IConfigurationBuilder builder)
   at Microsoft.Extensions.Configuration.ConfigurationManager.AddSource(IConfigurationSource source)
   at Microsoft.Extensions.Configuration.ConfigurationManager.Microsoft.Extensions.Configuration.IConfigurationBuilder.Add(IConfigurationSource source)
   at Microsoft.Extensions.Configuration.ConfigurationExtensions.Add[TSource](IConfigurationBuilder builder, Action`1 configureSource)
   at Microsoft.Extensions.Configuration.JsonConfigurationExtensions.AddJsonFile(IConfigurationBuilder builder, IFileProvider provider, String path, Boolean optional, Boolean reloadOnChange)
   at Microsoft.Extensions.Configuration.JsonConfigurationExtensions.AddJsonFile(IConfigurationBuilder builder, String path, Boolean optional, Boolean reloadOnChange)
   at Microsoft.Extensions.Hosting.HostingHostBuilderExtensions.<>c__DisplayClass11_0.<ConfigureDefaults>b__1(HostBuilderContext hostingContext, IConfigurationBuilder config)
   at Microsoft.AspNetCore.Hosting.BootstrapHostBuilder.RunDefaultCallbacks(ConfigurationManager configuration, HostBuilder innerBuilder)
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder..ctor(WebApplicationOptions options, Action`1 configureDefaults)
   at Microsoft.AspNetCore.Builder.WebApplication.CreateBuilder(String[] args)
   at Program.<Main>$(String[] args) in /src/ES.Kubernetes.Reflector/Program.cs:line 23
```

**Comment by winromulus** [comment]
Hi @conradreisch . To be honest I'm not sure why this might happen. The image was tested on ARM64 on multiple platforms, so it might be something with the underlying k8s cluster. I have the image running now on a few Raspberry PIs on ARM64 and they're working fine.

**Comment by conradreisch** [comment]
Hi @winromulus, thanks for the fast reply. The issue might be with [colima](https://github.com/abiosoft/colima), which is the docker runtime below k3d.
I'm trying to use microk8s instead and will post an update.

**Comment by conradreisch** [comment]
@winromulus 
Update: I failed to get to get microk8s running. Therefore, I temporarily used docker-desktop.
Result: reflector container is still crashing. Therefore, I'm more confident that the issue is related to the reflector image in combination with the MacBook.

System is:
- Mac OS Monterey (12.3)
- Chip Apple M1 Pro

Please let me know in case I can support with further information.

**Comment by conradreisch** [comment]
@winromulus 
Update No.2: reflector also fails on minikube with docker driver.
Result: It is most likely not: colima, k3d, docker or minikube

**Comment by conradreisch** [comment]
Update No.3:
It seems that the issue is related to the qemu virtual environment (which is used for docker on Mac).
So, unlike my initial thought, it is actually the AMD64 image that fails within the qemu x86_64 environment on ARM64.

I'm closing this issue, since the described setup is not a concern for the reflector dev team.
Thanks for your support!
