### ISSUE TITLE
HttpOperationException: Operation returned an invalid status code 'NotFound'

### ISSUE THREAD

**Issue by eratolekov** [emberstack/kubernetes-reflector#364]
Hi winromulus

I was trying to copy certificate with Reflector and I'm getting exception:

```
2023-07-09 13:32:06.604 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretMirror) Created prod/api-letsencrypt-stage-tls as a reflection of reflector/api-letsencrypt-stage-tls
2023-07-09 13:32:06.604 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretMirror) Auto-reflected reflector/api-letsencrypt-stage-tls where permitted. Created 1 - Updated 0 - Deleted 0 - Validated 0.
2023-07-09 13:32:06.605 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretMirror) Source reflector/api-letsencrypt-stage-tls no longer permits the auto reflection to prod/api-letsencrypt-stage-tls. Deleting prod/api-letsencrypt-stage-tls.
2023-07-09 13:32:06.615 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretMirror) Source reflector/api-letsencrypt-stage-tls no longer permits the auto reflection to prod/api-letsencrypt-stage-tls. Deleting prod/api-letsencrypt-stage-tls.
2023-07-09 13:32:06.621 +00:00 [ERR] (ES.Kubernetes.Reflector.Core.SecretWatcher) Faulted due to exception.
k8s.Autorest.HttpOperationException: Operation returned an invalid status code 'NotFound'
   at k8s.Kubernetes.SendRequestRaw(String requestContent, HttpRequestMessage httpRequest, CancellationToken cancellationToken)
   at k8s.AbstractKubernetes.k8s.ICoreV1Operations.DeleteNamespacedSecretWithHttpMessagesAsync(String name, String namespaceParameter, V1DeleteOptions body, String dryRun, Nullable`1 gracePeriodSeconds, Nullable`1 orphanDependents, String propagationPolicy, Nullable`1 pretty, IReadOnlyDictionary`2 customHeaders, CancellationToken cancellationToken)
   at k8s.CoreV1OperationsExtensions.DeleteNamespacedSecretAsync(ICoreV1Operations operations, String name, String namespaceParameter, V1DeleteOptions body, String dryRun, Nullable`1 gracePeriodSeconds, Nullable`1 orphanDependents, String propagationPolicy, Nullable`1 pretty, CancellationToken cancellationToken)
   at ES.Kubernetes.Reflector.Core.Mirroring.ResourceMirror`1.HandleUpsert(TResource resource, WatchEventType eventType, CancellationToken cancellationToken) in /src/ES.Kubernetes.Reflector/Core/Mirroring/ResourceMirror.cs:line 324
   at ES.Kubernetes.Reflector.Core.Mirroring.ResourceMirror`1.Handle(WatcherEvent notification, CancellationToken cancellationToken) in /src/ES.Kubernetes.Reflector/Core/Mirroring/ResourceMirror.cs:line 149
   at MediatR.NotificationPublishers.ForeachAwaitPublisher.Publish(IEnumerable`1 handlerExecutors, INotification notification, CancellationToken cancellationToken)
   at ES.Kubernetes.Reflector.Core.Watchers.WatcherBackgroundService`2.ExecuteAsync(CancellationToken stoppingToken) in /src/ES.Kubernetes.Reflector/Core/Watchers/WatcherBackgroundService.cs:line 78
   at ES.Kubernetes.Reflector.Core.Watchers.WatcherBackgroundService`2.ExecuteAsync(CancellationToken stoppingToken) in /src/ES.Kubernetes.Reflector/Core/Watchers/WatcherBackgroundService.cs:line 78
2023-07-09 13:32:06.627 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretWatcher) Session closed. Duration: 00:01:30.8924405. Faulted: True.
```

The certificate is:
```
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
...
spec:
  dnsNames:
    - api.example.com
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-apisix-stage
  secretName: api-letsencrypt-stage-tls
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: 'true'
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: prod
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: 'true'
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: prod
  usages:
    - digital signature
    - key encipherment
```

Reflector version:
7.0.151

K8s version:
1.25.2

The k8s names space `prod` exists.

**Comment by eratolekov** [comment]
Same exception for Reflector 7.0.190

```
2023-07-09 13:58:32.260 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretMirror) Created prod/api-letsencrypt-stage-tls as a reflection of reflector/api-letsencrypt-stage-tls
2023-07-09 13:58:32.260 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretMirror) Auto-reflected reflector/api-letsencrypt-stage-tls where permitted. Created 1 - Updated 0 - Deleted 0 - Validated 0.
2023-07-09 13:58:32.261 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretMirror) Source reflector/api-letsencrypt-stage-tls no longer permits the auto reflection to prod/api-letsencrypt-stage-tls. Deleting prod/api-letsencrypt-stage-tls.
2023-07-09 13:58:32.305 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretMirror) Source reflector/api-letsencrypt-stage-tls no longer permits the auto reflection to prod/api-letsencrypt-stage-tls. Deleting prod/api-letsencrypt-stage-tls.
2023-07-09 13:58:32.320 +00:00 [ERR] (ES.Kubernetes.Reflector.Core.SecretWatcher) Faulted due to exception.
k8s.Autorest.HttpOperationException: Operation returned an invalid status code 'NotFound'
   at k8s.Kubernetes.SendRequestRaw(String requestContent, HttpRequestMessage httpRequest, CancellationToken cancellationToken)
   at k8s.AbstractKubernetes.k8s.ICoreV1Operations.DeleteNamespacedSecretWithHttpMessagesAsync(String name, String namespaceParameter, V1DeleteOptions body, String dryRun, Nullable`1 gracePeriodSeconds, Nullable`1 orphanDependents, String propagationPolicy, Nullable`1 pretty, IReadOnlyDictionary`2 customHeaders, CancellationToken cancellationToken)
   at k8s.CoreV1OperationsExtensions.DeleteNamespacedSecretAsync(ICoreV1Operations operations, String name, String namespaceParameter, V1DeleteOptions body, String dryRun, Nullable`1 gracePeriodSeconds, Nullable`1 orphanDependents, String propagationPolicy, Nullable`1 pretty, CancellationToken cancellationToken)
   at ES.Kubernetes.Reflector.Core.Mirroring.ResourceMirror`1.HandleUpsert(TResource resource, WatchEventType eventType, CancellationToken cancellationToken) in /src/ES.Kubernetes.Reflector/Core/Mirroring/ResourceMirror.cs:line 322
   at ES.Kubernetes.Reflector.Core.Mirroring.ResourceMirror`1.Handle(WatcherEvent notification, CancellationToken cancellationToken) in /src/ES.Kubernetes.Reflector/Core/Mirroring/ResourceMirror.cs:line 86
   at MediatR.NotificationPublishers.ForeachAwaitPublisher.Publish(IEnumerable`1 handlerExecutors, INotification notification, CancellationToken cancellationToken)
   at ES.Kubernetes.Reflector.Core.Watchers.WatcherBackgroundService`2.ExecuteAsync(CancellationToken stoppingToken) in /src/ES.Kubernetes.Reflector/Core/Watchers/WatcherBackgroundService.cs:line 47
   at ES.Kubernetes.Reflector.Core.Watchers.WatcherBackgroundService`2.ExecuteAsync(CancellationToken stoppingToken) in /src/ES.Kubernetes.Reflector/Core/Watchers/WatcherBackgroundService.cs:line 45
2023-07-09 13:58:32.385 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretWatcher) Session closed. Duration: 00:00:49.3004267. Faulted: True.

```

**Comment by winromulus** [comment]
@eratolekov please post the annotations of the resulting secret created by cert-manager please (the source). Please ensure that the reflector annotations are present. This seems like a cert-manager problem.

**Comment by paulcsiki** [comment]
I am seeing the same problem with 7.1.238.
Secret:
`apiVersion: v1
kind: Secret
metadata:
  name: services-paulcsiki-com-tls
  namespace: traefik
  annotations:
    cert-manager.io/alt-names: '*.services.paulcsiki.com'
    cert-manager.io/certificate-name: services-paulcsiki-com
    cert-manager.io/common-name: '*.services.paulcsiki.com'
    cert-manager.io/ip-sans: ''
    cert-manager.io/issuer-group: cert-manager.io
    cert-manager.io/issuer-kind: ClusterIssuer
    cert-manager.io/issuer-name: production-acme-issuer
    cert-manager.io/uri-sans: ''
    reflector.v1.k8s.emberstack.com/reflection-allowed: 'true'
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: whoami,portainer,authentik,nextcloud,mailu,longhorn-system,adguard
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: 'true'
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: whoami,portainer,authentik,nextcloud,mailu,longhorn-system,adguard
data:
  tls.crt: >-
    removed
  tls.key: >-
    removed
type: kubernetes.io/tls
`

Adding readflow to the allowed namespaces and auto namespaces will result in the log below and then the secret yaml returns back before my change (I.e. readflow is no longer mentioned in the file)

Log:
`2024-01-30 21:04:29.702 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretMirror) Patched whoami/services-paulcsiki-com-tls as a reflection of traefik/services-paulcsiki-com-tls
2024-01-30 21:04:29.702 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretMirror) Auto-reflected traefik/services-paulcsiki-com-tls where permitted. Created 1 - Updated 7 - Deleted 0 - Validated 0.
2024-01-30 21:04:29.703 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretMirror) Source traefik/services-paulcsiki-com-tls no longer permits the auto reflection to readflow/services-paulcsiki-com-tls. Deleting readflow/services-paulcsiki-com-tls.
2024-01-30 21:04:29.758 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretMirror) Patched adguard/services-paulcsiki-com-tls as a reflection of traefik/services-paulcsiki-com-tls
2024-01-30 21:04:29.767 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretMirror) Patched longhorn-system/services-paulcsiki-com-tls as a reflection of traefik/services-paulcsiki-com-tls
2024-01-30 21:04:29.776 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretMirror) Patched mailu/services-paulcsiki-com-tls as a reflection of traefik/services-paulcsiki-com-tls
2024-01-30 21:04:29.785 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretMirror) Patched nextcloud/services-paulcsiki-com-tls as a reflection of traefik/services-paulcsiki-com-tls
2024-01-30 21:04:29.793 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretMirror) Patched authentik/services-paulcsiki-com-tls as a reflection of traefik/services-paulcsiki-com-tls
2024-01-30 21:04:29.802 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretMirror) Patched portainer/services-paulcsiki-com-tls as a reflection of traefik/services-paulcsiki-com-tls
2024-01-30 21:04:29.809 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretMirror) Patched whoami/services-paulcsiki-com-tls as a reflection of traefik/services-paulcsiki-com-tls
2024-01-30 21:04:29.809 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretMirror) Auto-reflected traefik/services-paulcsiki-com-tls where permitted. Created 0 - Updated 7 - Deleted 0 - Validated 0.
2024-01-30 21:04:29.809 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretMirror) Source traefik/services-paulcsiki-com-tls no longer permits the auto reflection to readflow/services-paulcsiki-com-tls. Deleting readflow/services-paulcsiki-com-tls.
2024-01-30 21:04:29.814 +00:00 [ERR] (ES.Kubernetes.Reflector.Core.SecretWatcher) Faulted due to exception.
k8s.Autorest.HttpOperationException: Operation returned an invalid status code 'NotFound', response body {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"secrets \"services-paulcsiki-com-tls\" not found","reason":"NotFound","details":{"name":"services-paulcsiki-com-tls","kind":"secrets"},"code":404}

   at k8s.Kubernetes.SendRequestRaw(String requestContent, HttpRequestMessage httpRequest, CancellationToken cancellationToken)
   at k8s.AbstractKubernetes.ICoreV1Operations_DeleteNamespacedSecretWithHttpMessagesAsync[T](String name, String namespaceParameter, V1DeleteOptions body, String dryRun, Nullable`1 gracePeriodSeconds, Nullable`1 orphanDependents, String propagationPolicy, Nullable`1 pretty, IReadOnlyDictionary`2 customHeaders, CancellationToken cancellationToken)
   at k8s.AbstractKubernetes.k8s.ICoreV1Operations.DeleteNamespacedSecretWithHttpMessagesAsync(String name, String namespaceParameter, V1DeleteOptions body, String dryRun, Nullable`1 gracePeriodSeconds, Nullable`1 orphanDependents, String propagationPolicy, Nullable`1 pretty, IReadOnlyDictionary`2 customHeaders, CancellationToken cancellationToken)
   at k8s.CoreV1OperationsExtensions.DeleteNamespacedSecretAsync(ICoreV1Operations operations, String name, String namespaceParameter, V1DeleteOptions body, String dryRun, Nullable`1 gracePeriodSeconds, Nullable`1 orphanDependents, String propagationPolicy, Nullable`1 pretty, CancellationToken cancellationToken)
   at ES.Kubernetes.Reflector.Core.Mirroring.ResourceMirror`1.HandleUpsert(TResource resource, WatchEventType eventType, CancellationToken cancellationToken) in /src/ES.Kubernetes.Reflector/Core/Mirroring/ResourceMirror.cs:line 325
   at ES.Kubernetes.Reflector.Core.Mirroring.ResourceMirror`1.Handle(WatcherEvent notification, CancellationToken cancellationToken) in /src/ES.Kubernetes.Reflector/Core/Mirroring/ResourceMirror.cs:line 150
   at MediatR.NotificationPublishers.ForeachAwaitPublisher.Publish(IEnumerable`1 handlerExecutors, INotification notification, CancellationToken cancellationToken)
   at ES.Kubernetes.Reflector.Core.Watchers.WatcherBackgroundService`2.ExecuteAsync(CancellationToken stoppingToken) in /src/ES.Kubernetes.Reflector/Core/Watchers/WatcherBackgroundService.cs:line 78
   at ES.Kubernetes.Reflector.Core.Watchers.WatcherBackgroundService`2.ExecuteAsync(CancellationToken stoppingToken) in /src/ES.Kubernetes.Reflector/Core/Watchers/WatcherBackgroundService.cs:line 78
2024-01-30 21:04:29.818 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretWatcher) Session closed. Duration: 00:06:55.1295232. Faulted: True.
2024-01-30 21:04:34.818 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretWatcher) Requesting V1Secret resources
2024-01-30 21:04:35.006 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretMirror) Auto-reflected traefik/services-paulcsiki-com-tls where permitted. Created 0 - Updated 0 - Deleted 0 - Validated 7.`

**Comment by paulcsiki** [comment]
I've had the exact same problem but I was editing the secret instead of the certificate's secret template.
