### ISSUE TITLE
k8s-reflector operator stuck during start up

### ISSUE THREAD

**Issue by ajaykumarmandapati** [emberstack/kubernetes-reflector#370]
Hi folks,
I did try to install the operator following the helm-chart [installation](https://artifacthub.io/packages/helm/emberstack/reflector#deployment-using-helm) and created a secret mentioned below :

```
apiVersion: v1
kind: Secret
metadata:
  namespace: reflector-test
  name: oidc-secret
  annotations:
   reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
   reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "istio-ingress"
data:
  clientID: <DUMMY_ID>
  clientSecret: <DUMMY_SECRET>   
```

I expect the operator to start normally and copy over the secret to `istio-ingress` namespace and then watch the `reflector-test` namespaced secret for any changes and sync them accordingly. However, in the operator logs I do see exceptions and does not proceed at all.

```
2023-08-08 13:15:17.046 +00:00 [INF] () Starting host
2023-08-08 13:15:17.424 +00:00 [INF] (ES.Kubernetes.Reflector.Core.NamespaceWatcher) Requesting V1Namespace resources
2023-08-08 13:15:17.444 +00:00 [INF] (ES.Kubernetes.Reflector.Core.SecretWatcher) Requesting V1Secret resources
2023-08-08 13:15:17.453 +00:00 [INF] (ES.Kubernetes.Reflector.Core.ConfigMapWatcher) Requesting V1ConfigMap resources
2023-08-08 13:17:28.236 +00:00 [ERR] (ES.Kubernetes.Reflector.Core.NamespaceWatcher) Faulted due to exception.
System.Net.Http.HttpRequestException: Connection timed out ([fd19:7543:4137::1]:443)
 ---> System.Net.Sockets.SocketException (110): Connection timed out
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|281_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp2ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at k8s.Kubernetes.SendRequestRaw(String requestContent, HttpRequestMessage httpRequest, CancellationToken cancellationToken)
   at k8s.AbstractKubernetes.k8s.ICoreV1Operations.ListNamespaceWithHttpMessagesAsync(Nullable`1 allowWatchBookmarks, String continueParameter, String fieldSelector, String labelSelector, Nullable`1 limit, String resourceVersion, String resourceVersionMatch, Nullable`1 timeoutSeconds, Nullable`1 watch, Nullable`1 pretty, IReadOnlyDictionary`2 customHeaders, CancellationToken cancellationToken)
   at k8s.WatcherExt.<>c__DisplayClass1_0`2.<<MakeStreamReaderCreator>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at k8s.Watcher`1.<>c.<CreateWatchEventEnumerator>b__21_1[TR](Task`1 t)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at k8s.Watcher`1.CreateWatchEventEnumerator(Func`1 streamReaderCreator, Action`1 onError, CancellationToken cancellationToken)+MoveNext()
   at k8s.Watcher`1.CreateWatchEventEnumerator(Func`1 streamReaderCreator, Action`1 onError, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at ES.Kubernetes.Reflector.Core.Watchers.WatcherBackgroundService`2.ExecuteAsync(CancellationToken stoppingToken) in /src/ES.Kubernetes.Reflector/Core/Watchers/WatcherBackgroundService.cs:line 45
   at ES.Kubernetes.Reflector.Core.Watchers.WatcherBackgroundService`2.ExecuteAsync(CancellationToken stoppingToken) in /src/ES.Kubernetes.Reflector/Core/Watchers/WatcherBackgroundService.cs:line 45
2023-08-08 13:17:28.248 +00:00 [INF] (ES.Kubernetes.Reflector.Core.NamespaceWatcher) Session closed. Duration: 00:02:10.8257841. Faulted: True.
```

What interests me is this bit `System.Net.Http.HttpRequestException: Connection timed out ([fd19:7543:4137::1]:443)` is there something additional that we would have to setup? in terms of networking for this work?

**Comment by ajaykumarmandapati** [comment]
@winromulus ? Can we get some help on this? 🤔

**Comment by winromulus** [comment]
@ajaykumarmandapati reflector tries to connect to the control plane API. Are you sure you don't have a firewall rule between the worker nodes and the control plane? Try opening a connection from another pod to the control plane API.
Also it seems your control plane is running on IPv6, which isn't a problem for reflector but please ensure that 443 is open in the firewall.

**Comment by ajaykumarmandapati** [comment]
<img width="1381" alt="image" src="https://github.com/emberstack/kubernetes-reflector/assets/47316512/52bb535d-ee6f-4764-ae8c-f4cf963cac43">

I think we do have that in place via this SG.

**Comment by winromulus** [comment]
@ajaykumarmandapati I really can't help debug this, but ensure that you can connect to the control plane from the worker nodes and the pods inside them (if using vxlan or NAT).
A simple telnet or curl from inside the node SSH and from inside a pod will suffice to debug this. Any k8s extension running on worker nodes will require this to be functional.
I'm going to close this issue since it's not a reflector issue but a k8s self-hosted issue.

**Comment by winromulus** [comment]
You can still reply to this for general debug (if needed), but please keep the issue closed unless this is strictly related to reflector.
