### ISSUE TITLE
Reflector pod restart count is really high in AKS

### ISSUE THREAD

**Issue by dhananjaya-senanayake** [emberstack/kubernetes-reflector#76]
Error Log
```
2020-08-19 07:37:27.881 +00:00 [INF] (ES.Kubernetes.Reflector.Host.Program) Starting host
2020-08-19 07:37:34.272 +00:00 [INF] (ES.Kubernetes.Reflector.CertManager.Monitor) V1CustomResourceDefinition Certificate in group cert-manager.io versions updated to ["v1alpha2", "v1alpha3"]
2020-08-19 07:37:41.981 +00:00 [WRN] (ES.Kubernetes.Reflector.Secrets.Mirror) Cannot create reflection Secret stage-choreo-system/stage-choreo-system-wildcard-tls for cert-manager/stage-choreo-system-wildcard-tls. Found conflicting Secret with the same name.
2020-08-19 13:07:23.580 +00:00 [ERR] (ES.Kubernetes.Reflector.ConfigMaps.Mirror) V1Namespace watcher Faulted
System.Net.Http.HttpRequestException: Connection timed out
 ---> System.Net.Sockets.SocketException (110): Connection timed out
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at k8s.WatcherDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Rest.RetryDelegatingHandler.<>c__DisplayClass11_0.<<SendAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Rest.RetryDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at k8s.Kubernetes.ListNamespaceWithHttpMessagesAsync(Nullable`1 allowWatchBookmarks, String continueParameter, String fieldSelector, String labelSelector, Nullable`1 limit, String resourceVersion, Nullable`1 timeoutSeconds, Nullable`1 watch, String pretty, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at ES.Kubernetes.Reflector.Core.Mirroring.ResourceMirror`2.<>c.<<-ctor>b__7_2>d.MoveNext() in /src/ES.Kubernetes.Reflector.Core/Mirroring/ResourceMirror.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at ES.Kubernetes.Reflector.Core.Monitoring.ManagedWatcher`3.Start() in /src/ES.Kubernetes.Reflector.Core/Monitoring/ManagedWatcher.cs:line 100
2020-08-19 13:07:28.446 +00:00 [ERR] (Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService) Health check ES.Kubernetes.Reflector.ConfigMaps.Mirror completed after 0.0012ms with status Unhealthy and 'null'
2020-08-19 13:07:33.242 +00:00 [ERR] (Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService) Health check ES.Kubernetes.Reflector.ConfigMaps.Mirror completed after 0.002ms with status Unhealthy and 'null'
2020-08-19 13:07:38.441 +00:00 [ERR] (Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService) Health check ES.Kubernetes.Reflector.ConfigMaps.Mirror completed after 0.002ms with status Unhealthy and 'null'
2020-08-19 13:07:43.242 +00:00 [ERR] (Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService) Health check ES.Kubernetes.Reflector.ConfigMaps.Mirror completed after 0.0009ms with status Unhealthy and 'null'
2020-08-19 13:07:48.441 +00:00 [ERR] (Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService) Health check ES.Kubernetes.Reflector.ConfigMaps.Mirror completed after 0.0017ms with status Unhealthy and 'null'
2020-08-19 13:07:53.242 +00:00 [ERR] (Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService) Health check ES.Kubernetes.Reflector.ConfigMaps.Mirror completed after 0.0013ms with status Unhealthy and 'null'
```
Pod restart count 
`reflector-7f9875dbfd-9n4dk                   1/1     Running   101        7d15h`

version
`5.0.10`

AKS Version
v1.16.13

**Comment by winromulus** [comment]
@dhananjaya-senanayake - please try version 5.3.1 (latest)
I made some changes which should reduce the amount of restarts and improve stability on AKS
